version: '3'
services:
  web:
    build: .
    container_name: railsapp
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - /var/tmp
      # socketファイルの共有
      - sockets:/app/tmp/sockets
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
    networks:
      - railsnet
  db:
    image: mysql:5.7
    container_name: railsdb
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: railsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      # host:container　となっているのでhost側のportをかぶらないようにする
    restart: always
    ports:
      - 3306:3306
    networks:
      - railsnet
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
      #socketファイルの共有
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - web
    networks:
      - railsnet

networks:
  railsnet:

#このボリュームでsocketsを指定することでnginxとの連携が行われる。
volumes:
  sockets:

